# Generated by Django 4.1.5 on 2023-03-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('place_id', models.CharField(max_length=300)),
                ('business_status', models.CharField(max_length=100)),
                ('formatted_address', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=100)),
                ('opening_hours', models.CharField(max_length=100)),
                ('plus_code', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('reviews', models.TextField()),
                ('types', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('user_ratings_total', models.IntegerField()),
                ('vicinity', models.CharField(max_length=100)),
                ('website', models.URLField()),
            ],
        ),
    ]
