# Generated by Django 4.1.5 on 2023-03-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='reviews',
            field=models.TextField(default=''),
        ),
    ]
