# Generated by Django 4.1.5 on 2023-03-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_place_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='mydate',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
